name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/devops-ramp-up-frontend:${{ github.sha }}
          
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ${{ secrets.EC2_USERNAME }}
            key: ${{ secrets.EC2_PRIVATE_KEY }}
            script: |
                sudo usermod -aG docker $USER
                newgrp docker
                docker kill $(docker ps -q)
                docker rm $(docker ps -a -q)
                docker rmi $(docker images -a -q) -f
                docker pull ${{ secrets.DOCKER_USERNAME }}/devops-ramp-up-frontend:latest
                docker run -d --name frontend -p 8080:8080 \
                    -e PORT=8080 \
                    -e AUTH_API_ADDRESS=http://${{ secrets.ALB_DNS }}:8000 \
                    -e TODOS_API_ADDRESS=http://${{ secrets.ALB_DNS }}:8082 \
                    -e ZIPKIN_URL=http://${{ secrets.ZIPKIN_IP }}:9411/api/v2/spans \
                    ${{ secrets.DOCKER_USERNAME }}/devops-ramp-up-frontend:latest