name: Unit Testing

on:
  pull_request:
    branches:
        - main
    types: [opened, reopened]


jobs: 
    Run-Unit-Test:
        runs-on: 
          ubuntu-latest

        steps: 
            - name: Checkout code
              uses: actions/checkout@v2
            
            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Build and Push Docker image
              uses: docker/build-push-action@v4
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKER_USERNAME }}/devops-ramp-up-frontend:testing-${{ github.sha }}
                
            - name: Run unit tests in Docker container
              run: |
                    docker pull ${{ secrets.DOCKER_USERNAME }}/devops-ramp-up-frontend:testing-${{ github.sha }}
                    docker run --name frontend-testing -p 8080:8080 \
                    ${{ secrets.DOCKER_USERNAME }}/devops-ramp-up-frontend:testing-${{ github.sha }} test